#
# Test-job template
#

.ensembl_test_template:
  image: dockerhub.ebi.ac.uk/ensembl-infrastructure/ensembl-ci-docker-images:${PERL_VERSION}

  services:
    - mysql:5.6

  variables:
    # FIXME: set some password for both users
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_USER: "travis"
    MYSQL_PASSWORD: ""
    USER: "gitlabci"

  before_script:
    - apt-get update
    - apt-get install -y build-essential cpanminus git
    - apt-get install -y default-libmysqlclient-dev default-mysql-client
    - apt-get install -y libssl-dev sqlite3
    - echo "CI_COMMIT_REF_NAME = ${CI_COMMIT_REF_NAME}"
    - export ENSEMBL_BRANCH='master'
    - if [[ ${CI_COMMIT_REF_NAME} =~ ^release\/[0-9]+$ ]]; then export ENSEMBL_BRANCH=${CI_COMMIT_REF_NAME}; fi
    - echo "ENSEMBL_BRANCH = ${ENSEMBL_BRANCH}"
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-hdf5.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-vep.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch=${ENSEMBL_BRANCH} --depth=1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch=release-1-6-924 --depth=1 https://github.com/bioperl/bioperl-live.git
    - git clone --branch=1.3.2 --depth=1 https://github.com/samtools/htslib.git
    - cd htslib
    - make
    - export HTSLIB_DIR=$(pwd -P)
    - cd ..
    - ( cd ensembl-variation/C_code/ && make )
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm -v --installdeps --with-recommends --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n DBD::SQLite
    - cp travisci/MultiTestDB.conf.gitlabci  t/MultiTestDB.conf
    - mysql -u root -h mysql -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

#
# Test jobs
#

test:perl5.14:
  stage: test
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.14"
    COVERALLS: "false"
  script:
    - ./travisci/harness.sh

test:perl5.30:
  stage: test
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.30"
    # Note: relies on the secret variable COVERALLS_REPO_TOKEN for report uploads to work
    COVERALLS: "true"
  script:
    - ./travisci/harness.sh
