language: "perl"

perl:
  - "5.14"

env:
  - COVERALLS=false

before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install unzip
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip

install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm Catalyst::Runtime 
    - cpanm - Catalyst::Plugin::ConfigLoader Catalyst::Action::RenderView Catalyst::Plugin::Static::Simple
    - cpanm Catalyst::Devel
    - cpanm -v --installdeps --with-recommends --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp travisci/MultiTestDB.conf.travisci t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
  on_success: always
  on_failure: always
