language: "perl"

perl:
  - "5.14"

sudo: false

addons:
  apt:
    packages:
    - unzip

env:
  - COVERALLS=false

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip
    - cd ensembl-variation/C_code/
    - make
    - cd ../../
    - git clone --branch master --depth 1 https://github.com/samtools/htslib.git
    - cd htslib
    - make install

install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm -v --installdeps --with-recommends --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm Bio::DB::HTS
    - cp travisci/MultiTestDB.conf.travisci t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
